### ISSUE TITLE
Zoom to layer is slow with a spatial index

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1056]
With the last OrbisGIS version, the renderer has an ultra-low latency before drawing a full layer with a spatial index.

To test
1. Drag and drop a table in the TOC (without any spatial index)
2. Zoom on it
3. Do a zoom to layer

Repeat the same operations with a spatial index.

**Comment by ebocher** [comment]
This bug appears only with an H2(GIS) database...

**Comment by ebocher** [comment]
Using H2 database profiling option (TRACE_LEVEL_FILE=2), returns

/*SQL #:235392 t:2648*/SELECT  _ROWID_, *  FROM \"ROUTE_DB\";
2016-08-25 16:24:03 command: slow query: 4 539 ms

**Comment by SPalominos** [comment]
Linked to H2database issue :  h2database/h2database#385

**Comment by SPalominos** [comment]
So as @nicolas-f  says in the h2database issue, it was fixed and will be available in the next h2database release.

**Comment by SPalominos** [comment]
The issue still not resolved by the new version of h2database (1.4.193).
Issue #h2database/h2database#385 stills open.

**Comment by gpetit** [comment]
Maybe this issue will be resolved with the new h2database release (1.4.194) ?

**Comment by ebocher** [comment]
Tested with 1.4.194 and the bug still exist. 
@gpetit could you confirm ?

**Comment by nicolas-f** [comment]
The computation of the envelope is not accelerated by the spatial index.

**Comment by ebocher** [comment]
This is not due only to the computation of the envelope because without spatial index the rendering is faster than with a spatial index.

**Comment by gpetit** [comment]
I just tried with a fresh version of OG.
I displayed two same imported shapefiles (BATI_INDIFFERENCIE - dept44).
To make an extended zoom, I don't see any differences (in both cases moreless 5s).
But when I zoom in and out at a more high scale, the display is quite faster with the layer that has the spatial index (Almost instantaneous vs 1s).

**Comment by nicolas-f** [comment]
After some test I found that h2 still use spatial index only on linked shape files. So there is a missing fix on the index cost on h2gis side. here:

https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2TableIndex.java#L163

We have to copy paste new system index code of h2.

**Comment by gpetit** [comment]
@nicolas-f you mean that the optimization is currently only working with linked tables ?
In my previous test, I was using imported shape files.

**Comment by nicolas-f** [comment]
The fix done on h2 side works only with imported shape files. The issue is still there for linked shape files with spatial index.

**Comment by gpetit** [comment]
Hum I made a new test with linked shape file (ZONE_VEGETATION on dept 44) and here again I can see a huge difference between layer1 without spatial index and layer2 with spatial index.
- layer2 is displayed in quasi real time.
- layer1 takes at least 1s to display a small area

**Comment by nicolas-f** [comment]
Sorry I did not explain the issue. Using spatial index for iterating over all geometries (viewing all geometries) is slower than using primary key index. 

On linked shape files H2 still use spatial index over primary key index even if there is no spatial predicates, this is because our implementation of the PK column return the wrong *index cost* (a cost > than spatial index)

The most easy way to identify this issue is by running the following query on the linked shape file (with and without spatial index)

```sql
EXPLAIN SELECT * FROM BIG_LINKED_SHAPEFILE ORDER BY PK
```

You will see that H2 will use spatial index on this query, and this is why @ebocher see a slowdown of drawing with the full extent.

# Linked shape file without spatial index
```sql
Execute request 1/1: explain select * from "GIS.OSM_BUILDINGS_A_FREE_1" order by pk

PLAN(VARCHAR)                  
SELECT
    "GIS.OSM_BUILDINGS_A_FREE_1".PK,
    "GIS.OSM_BUILDINGS_A_FREE_1".THE_GEOM,
    "GIS.OSM_BUILDINGS_A_FREE_1".OSM_ID,
    "GIS.OSM_BUILDINGS_A_FREE_1".CODE,
    "GIS.OSM_BUILDINGS_A_FREE_1".FCLASS,
    "GIS.OSM_BUILDINGS_A_FREE_1".NAME,
    "GIS.OSM_BUILDINGS_A_FREE_1".TYPE
FROM PUBLIC."GIS.OSM_BUILDINGS_A_FREE_1"
    /* PUBLIC."GIS.OSM_BUILDINGS_A_FREE_1.PK_INDEX_A" */
ORDER BY 1
/* index sorted */ 
```

## Linked shape file with index 

*spatial index name INDEX_A*

```sql
Execute request 1/1: explain select * from "GIS.OSM_BUILDINGS_A_FREE_1" order by pk

PLAN(VARCHAR)                  
SELECT
    "GIS.OSM_BUILDINGS_A_FREE_1".PK,
    "GIS.OSM_BUILDINGS_A_FREE_1".THE_GEOM,
    "GIS.OSM_BUILDINGS_A_FREE_1".OSM_ID,
    "GIS.OSM_BUILDINGS_A_FREE_1".CODE,
    "GIS.OSM_BUILDINGS_A_FREE_1".FCLASS,
    "GIS.OSM_BUILDINGS_A_FREE_1".NAME,
    "GIS.OSM_BUILDINGS_A_FREE_1".TYPE
FROM PUBLIC."GIS.OSM_BUILDINGS_A_FREE_1"
    /* PUBLIC.INDEX_A */
ORDER BY 1 
```

**Comment by gpetit** [comment]
So if I understand well (sorry if I'm a bit confused), you say that PK should always win against spatial index. But right now, when there is a spatial index, PK is not used.

If I'm right it means that PK should be more efficient than spatial index ... but considering my new tests, I think its more complex than that. Below is a small comparaison between full extent and small extent (USING ZONE_VEGETATION - dept 44 linked table)

Full extent
- with spatial index : 31s
- without spatial index : 10s

Zoom from "full extent" to a small area
- with spatial index : 0s
- without spatial index : 4s

So spatial index wins on small extent

**Comment by nicolas-f** [comment]
I never say PK should be always used.

> iterating over all geometries (viewing all geometries) is slower than using primary key index

> this is why @ebocher see a slowdown of drawing with the full extent.

>H2 still use spatial index over primary key index even if there is no spatial predicates

The rule is to use spatial index only if there is spatial predicates. So you will not loose 21s by iterating over all rows using R-Tree index.

**Comment by ebocher** [comment]
Fix thanks to @nicolas-f
